# GetCratesKeys config.yml
# 여기서는 각 행동 별 열쇠 드랍 확률을 설정할 수 있습니다.

# 열쇠 드랍 - true는 활성화, false는 비활성화.
# 기본 설정: true
keys_drop_enabled: true

# 최대 확률 단위 - 총 확률은 max_chance 분의 base_chance + level x multiplier 확률. 1 이상의 10의 제곱 단위의 정수 추천.
# 기본 설정: 10000
max_chance: 10000

#  ====================== # 열 쇠 # ======================  #
# | 열쇠 추가 방법:                                       | #
# | total: [총 열쇠 종류 갯수]                            | #
# | 번호(정수):                                           | #
# |   enabled: [true / false] (해당 열쇠 드랍 여부)       | #
# |   crate_name: [상자 이름]                             | #
# |   command: [SpecializedCrate 열쇠 지급 명령어]        | #
# | 상자 이름은 색코드 비사용 추천 (가시성)               | #
# | 열쇠 지급 명령어는 /를 빼고 입력                      | #
#  =======================================================  #
keys:
  total: 1
  1:
    enabled: true
    crate_name: 판도라의 상자
    command:

#  ====================== # 삽 질 # ======================  #
# | 블럭 추가 방법:                                       | #
# | 대문자 블럭 이름:                                     | #
# |   enabled: [true / false] (캤을 때 열쇠 드랍)         | #
# |   base_chance: [max_chance 분의 base_chance]          | #
# |   multiplier_enabled: [true / false] (레벨 당 증가)   | #
# |   multiplier: [레벨 당 증가 확률]                     | #
# | true는 활성화, false는 비활성화                       | #
#  =======================================================  #
digging:
  GRASS_BLOCK:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  DIRT:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  SAND:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  GRAVEL:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  SOUL_SAND:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  SOUL_SOIL:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  CLAY:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  COARSE_DIRT:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  RED_SAND:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  ROOTED_DIRT:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  MYCELIUM:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  PODZOL:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  MUD:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  POWDER_SNOW:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  SNOW:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  SNOW_BLOCK:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

#  ====================== # 농 사 # ======================  #
# | 블럭 추가 방법:                                       | #
# | 대문자 블럭 이름:                                     | #
# |   enabled: [true / false] (캤을 때 열쇠 드랍)         | #
# |   base_chance: [max_chance 분의 base_chance]          | #
# |   multiplier_enabled: [true / false] (레벨 당 증가)   | #
# |   multiplier: [레벨 당 증가 확률]                     | #
# | true는 활성화, false는 비활성화                       | #
#  =======================================================  #
farming:
  WHEAT_SEEDS:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  POTATO:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  CARROT:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  BEETROOT_SEEDS:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  PUMPKIN:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  MELON:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  SWEET_BERRIES:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  GLOW_BERRIES:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  SUGAR_CANE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

#  ====================== # 낚 시 # ======================  #
# | fishing:                                              | #
# |   enabled: [true / false] (낚시 성공 시 열쇠 드랍)    | #
# |   base_chance: [max_chance 분의 base_chance]          | #
# |   multiplier_enabled: [true / false] (레벨 당 증가)   | #
# |   multiplier: [레벨 당 증가 확률]                     | #
# | true는 활성화, false는 비활성화                       | #
#  =======================================================  #
fishing:
  fishing:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

#  ====================== # 광 질 # ======================  #
# | 블럭 추가 방법:                                       | #
# | 대문자 블럭 이름:                                     | #
# |   enabled: [true / false] (캤을 때 열쇠 드랍)         | #
# |   base_chance: [max_chance 분의 base_chance]          | #
# |   multiplier_enabled: [true / false] (레벨 당 증가)   | #
# |   multiplier: [레벨 당 증가 확률]                     | #
# | true는 활성화, false는 비활성화                       | #
#  =======================================================  #
mining:
  COAL_ORE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  COPPER_ORE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  IRON_ORE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  LAPIS_ORE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  GOLD_ORE:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  REDSTONE_ORE:
    enabled: true
    base_chance: 100
    multiplier_enabled: true
    multiplier: 1

  DIAMOND_ORE:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  EMERALD_ORE:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  NETHER_GOLD_ORE:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  NETHER_QUARTZ_ORE:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1

  ANCIENT_DEBRIS:
    enabled: true
    base_chance: 1000
    multiplier_enabled: true
    multiplier: 1
