# GetCratesKeys config.yml
# 오타 수정 및 궁금한 내용은 Derman_e (더맨이 / harry1725@naver.com) 에게 연락 바람
# 여기서는 열쇠에 대한 전체 사항을 설정할 수 있습니다.
#
# ======================= # 설 정 # ======================
# 열쇠 전체 설정 방법:
# config:
#   enabled: < true / false >
#   - 전체 열쇠 드랍 여부. true는 활성화, false는 비활성화
#
#   changeSave: < # >
#   - 서버에서 블럭이 파괴되거나 수확될 때 # 개마다 저장되는지 설정. 0 미만은 비활성화. 기본값은 1000.
#   - 저장 실패로 인한 크래시가 자주 뜨거나 서버 렉이 너무 많이 걸린다 싶으면 끄거나 숫자 늘리는 것을 추천
#
#   connectionSave: < # >
#   - 플레이어가 서버에 접속하거나 접속을 해제할 때 # 번마다 저장되는지 설정. 0 미만은 비활성화. 기본값은 20.
#   - 저장 실패로 인한 크래시가 자주 뜨거나 서버 렉이 너무 많이 걸린다 싶으면 끄거나 숫자 늘리는 것을 추천
#
#   maxChance: < # >
#   - 최대 확률 단위 - 총 확률은 maxChance 분의 baseChance + Aureliumlevel * multiplier 확률.
#   - 1이상의 10의 제곱 단위의 정수 추천. 기본 설정은 100000 (baseChance가 1이면 0.001 % 확률)
#
#   multiplierEnabled: < true / false >
#   - 전체 아우렐리움 스킬 배수 적용 여부. true는 활성화, false는 비활성화
#
#   dropBoost:
#     enabled: < true / false >
#     - 전체 열쇠에 대하여 드랍 부스트 적용. true는 활성화, false는 비활성화
#
#     amount: < # >
#     - 전체 열쇠에 대하여 #개의 추가 갯수 드랍 부스트 적용. 1 미만은 비활성화
#
#     chance: < -100 ~ # >
#     - 전체 열쇠에 대하여 # %의 추가 확률 드랍 부스트 적용. 0 은 비활성화
#
#   ceiling:
#     enabled: < true / false >
#     - 천장 시스템 설정. true는 활성화, false는 비활성화
#
#     excavationMax / farmingMax / fishingMax / foragingMax / miningMax : < # >
#     - 천장을 찍을 때까지 필요한 행동 횟수
# ========================================================
config:
  enabled: true
  changeSave: 1000
  connectionSave: 20

  maxChance: 100000                    # 1 / 100000 * 100 = 0.001 %

  multiplierEnabled: false

  dropBoost:
    enabled: false

    amount: -1
    chance: 0

  ceiling:
    enabled: true

    excavationMax: 10000
    farmingMax: 10000
    fishingMax: 300
    foragingMax: 5000
    miningMax: 500
    fightingMax: 500

